version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    user: '1000'
    ports:
      - '3000:3000'
    volumes:
      - '$PWD/data:/var/lib/grafana'
      - '$PWD/grafana.inc:/etc/grafana/grafana.ini'