version: '3.8'
services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    restart: always
    user: '1000'
    ports:
      - '8428:8428'
    volumes:
      - '$PWD/data:/victoria-metrics-data'
    command:
      - "--retentionPeriod=5y"